### ISSUE TITLE
Add phpmyadmin

### ISSUE THREAD

**Issue by elecoest** [cavo789/docker_joomla_restore#1]
to install phpmyadmin  :  

```
  phpmyadmin:
    image: phpmyadmin
    container_name: ${CONTAINER_PREFIX:-joomla}-phpmyadmin
    restart: always
    depends_on:
      joomladb:
        condition: service_healthy
    ports:
      - 8081:80
    environment:
      - PMA_HOST=joomladb
      - PMA_PASSWORD=${DB_ROOT_PASSWORD:-rootpass}
    networks:
      - joomla_network
```

in JOOMLADB you must set
`      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpass}
`
